apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-cache-pvc
  namespace: apostapro-ml
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2
