"""Adiciona tabela para posts de redes sociais

Revision ID: d3ff1c5ece16
Revises: 728a1893329a
Create Date: 2025-08-06 22:22:06.843588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ff1c5ece16'
down_revision = '728a1893329a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_redes_sociais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clube_id', sa.Integer(), nullable=False, comment='Referência ao clube dono do post'),
    sa.Column('rede_social', sa.String(length=50), nullable=False, comment="Plataforma de rede social (ex: 'Twitter', 'Instagram', 'Facebook')"),
    sa.Column('post_id', sa.String(length=100), nullable=False, comment='ID único do post na plataforma de origem'),
    sa.Column('conteudo', sa.Text(), nullable=False, comment='Conteúdo textual do post'),
    sa.Column('data_postagem', sa.DateTime(timezone=True), nullable=False, comment='Data e hora em que o post foi publicado'),
    sa.Column('curtidas', sa.Integer(), nullable=False, comment='Número de curtidas/reactions do post'),
    sa.Column('comentarios', sa.Integer(), nullable=False, comment='Número de comentários no post'),
    sa.Column('compartilhamentos', sa.Integer(), nullable=False, comment='Número de compartilhamentos/retweets'),
    sa.Column('url_post', sa.Text(), nullable=True, comment='URL direta para o post na rede social'),
    sa.Column('midia_url', sa.Text(), nullable=True, comment='URL da mídia anexada ao post (imagem/vídeo)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rede_social IN ('Twitter', 'Instagram', 'Facebook', 'YouTube', 'TikTok', 'Outro')", name='ck_posts_rede_social_valida'),
    sa.ForeignKeyConstraint(['clube_id'], ['clubes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index('idx_posts_redes_sociais_clube', 'posts_redes_sociais', ['clube_id'], unique=False)
    op.create_index('idx_posts_redes_sociais_data', 'posts_redes_sociais', ['data_postagem'], unique=False)
    op.create_index('idx_posts_redes_sociais_engajamento', 'posts_redes_sociais', ['curtidas', 'comentarios', 'compartilhamentos'], unique=False)
    op.create_index('idx_posts_redes_sociais_rede', 'posts_redes_sociais', ['rede_social'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_posts_redes_sociais_rede', table_name='posts_redes_sociais')
    op.drop_index('idx_posts_redes_sociais_engajamento', table_name='posts_redes_sociais')
    op.drop_index('idx_posts_redes_sociais_data', table_name='posts_redes_sociais')
    op.drop_index('idx_posts_redes_sociais_clube', table_name='posts_redes_sociais')
    op.drop_table('posts_redes_sociais')
    # ### end Alembic commands ###
