"""Add advanced stats: xG, xA, tactical formations

Revision ID: 00f0fe29f908
Revises: 
Create Date: 2025-08-03 22:00:43.495106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f0fe29f908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estatisticas_jogador_competicao', sa.Column('xg', sa.Float(), nullable=True, comment='Expected Goals do jogador'))
    op.add_column('estatisticas_jogador_competicao', sa.Column('xa', sa.Float(), nullable=True, comment='Expected Assists do jogador'))
    op.add_column('estatisticas_jogador_competicao', sa.Column('posicao_principal', sa.String(length=20), nullable=True, comment='Posição principal jogada na competição'))
    op.add_column('estatisticas_jogador_competicao', sa.Column('minutos_por_jogo', sa.Float(), nullable=True, comment='Média de minutos por jogo'))
    op.add_column('estatisticas_partidas', sa.Column('xg_casa', sa.Float(), nullable=True, comment='Expected Goals do time da casa'))
    op.add_column('estatisticas_partidas', sa.Column('xg_visitante', sa.Float(), nullable=True, comment='Expected Goals do time visitante'))
    op.add_column('estatisticas_partidas', sa.Column('xa_casa', sa.Float(), nullable=True, comment='Expected Assists do time da casa'))
    op.add_column('estatisticas_partidas', sa.Column('xa_visitante', sa.Float(), nullable=True, comment='Expected Assists do time visitante'))
    op.add_column('estatisticas_partidas', sa.Column('formacao_casa', sa.String(length=20), nullable=True, comment='Formação tática do time da casa (ex: 4-3-3)'))
    op.add_column('estatisticas_partidas', sa.Column('formacao_visitante', sa.String(length=20), nullable=True, comment='Formação tática do time visitante (ex: 4-3-3)'))
    op.create_index('idx_estatisticas_partida_formacao', 'estatisticas_partidas', ['formacao_casa', 'formacao_visitante'], unique=False)
    op.create_index('idx_estatisticas_partida_xg', 'estatisticas_partidas', ['xg_casa', 'xg_visitante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_estatisticas_partida_xg', table_name='estatisticas_partidas')
    op.drop_index('idx_estatisticas_partida_formacao', table_name='estatisticas_partidas')
    op.drop_column('estatisticas_partidas', 'formacao_visitante')
    op.drop_column('estatisticas_partidas', 'formacao_casa')
    op.drop_column('estatisticas_partidas', 'xa_visitante')
    op.drop_column('estatisticas_partidas', 'xa_casa')
    op.drop_column('estatisticas_partidas', 'xg_visitante')
    op.drop_column('estatisticas_partidas', 'xg_casa')
    op.drop_column('estatisticas_jogador_competicao', 'minutos_por_jogo')
    op.drop_column('estatisticas_jogador_competicao', 'posicao_principal')
    op.drop_column('estatisticas_jogador_competicao', 'xa')
    op.drop_column('estatisticas_jogador_competicao', 'xg')
    # ### end Alembic commands ###
