"""Initial schema with all base tables

Revision ID: 2f351926c833
Revises: d8bdb9b0920d
Create Date: 2025-08-08 07:44:27.758670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f351926c833'
down_revision = 'd8bdb9b0920d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competicoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('contexto', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'contexto', name='uq_competicao_nome_contexto')
    )
    op.create_index('idx_competicoes_ativa', 'competicoes', ['ativa'], unique=False)
    op.create_index('idx_competicoes_contexto', 'competicoes', ['contexto'], unique=False)
    op.create_index('idx_competicoes_nome', 'competicoes', ['nome'], unique=False)
    op.create_table('paises_clubes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo_iso', sa.String(length=3), nullable=True),
    sa.Column('continente', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('paises_jogadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo_iso', sa.String(length=3), nullable=True),
    sa.Column('continente', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('clubes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=500), nullable=True),
    sa.Column('url_fbref', sa.Text(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('fundacao', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['paises_clubes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clubes_ativo', 'clubes', ['ativo'], unique=False)
    op.create_index('idx_clubes_nome', 'clubes', ['nome'], unique=False)
    op.create_index('idx_clubes_pais', 'clubes', ['pais_id'], unique=False)
    op.create_table('links_para_coleta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competicao_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('ultimo_erro', sa.Text(), nullable=True),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pendente', 'processando', 'concluido', 'erro')", name='ck_links_status'),
    sa.ForeignKeyConstraint(['competicao_id'], ['competicoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_links_competicao', 'links_para_coleta', ['competicao_id'], unique=False)
    op.create_index('idx_links_processado', 'links_para_coleta', ['processado_em'], unique=False)
    op.create_index('idx_links_status', 'links_para_coleta', ['status'], unique=False)
    op.create_index('idx_links_tipo', 'links_para_coleta', ['tipo'], unique=False)
    op.create_table('estatisticas_clube',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clube_id', sa.Integer(), nullable=False),
    sa.Column('competicao_id', sa.Integer(), nullable=False),
    sa.Column('temporada', sa.String(length=20), nullable=False),
    sa.Column('jogos', sa.Integer(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=True),
    sa.Column('empates', sa.Integer(), nullable=True),
    sa.Column('derrotas', sa.Integer(), nullable=True),
    sa.Column('gols_pro', sa.Integer(), nullable=True),
    sa.Column('gols_contra', sa.Integer(), nullable=True),
    sa.Column('saldo_gols', sa.Integer(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('posicao', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clube_id'], ['clubes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competicao_id'], ['competicoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clube_id', 'competicao_id', 'temporada', name='uq_estatistica_clube_temporada')
    )
    op.create_index('idx_estatisticas_clube_clube', 'estatisticas_clube', ['clube_id'], unique=False)
    op.create_index('idx_estatisticas_clube_competicao', 'estatisticas_clube', ['competicao_id'], unique=False)
    op.create_index('idx_estatisticas_clube_temporada', 'estatisticas_clube', ['temporada'], unique=False)
    op.create_table('jogadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=500), nullable=True),
    sa.Column('url_fbref', sa.Text(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('posicao', sa.String(length=50), nullable=True),
    sa.Column('pe_preferido', sa.String(length=20), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('clube_atual_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('aposentado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clube_atual_id'], ['clubes.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['paises_jogadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jogadores_ativo', 'jogadores', ['ativo'], unique=False)
    op.create_index('idx_jogadores_clube_atual', 'jogadores', ['clube_atual_id'], unique=False)
    op.create_index('idx_jogadores_nome', 'jogadores', ['nome'], unique=False)
    op.create_index('idx_jogadores_pais', 'jogadores', ['pais_id'], unique=False)
    op.create_index('idx_jogadores_posicao', 'jogadores', ['posicao'], unique=False)
    op.create_table('noticias_clubes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clube_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('url_noticia', sa.String(length=500), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('conteudo_completo', sa.Text(), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.Column('imagem_destaque', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clube_id'], ['clubes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_noticia')
    )
    op.create_index('idx_noticias_clube', 'noticias_clubes', ['clube_id'], unique=False)
    op.create_index('idx_noticias_data', 'noticias_clubes', ['data_publicacao'], unique=False)
    op.create_index('idx_noticias_fonte', 'noticias_clubes', ['fonte'], unique=False)
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competicao_id', sa.Integer(), nullable=False),
    sa.Column('clube_casa_id', sa.Integer(), nullable=False),
    sa.Column('clube_visitante_id', sa.Integer(), nullable=False),
    sa.Column('data_partida', sa.Date(), nullable=True),
    sa.Column('horario', sa.String(length=10), nullable=True),
    sa.Column('rodada', sa.String(length=50), nullable=True),
    sa.Column('temporada', sa.String(length=20), nullable=True),
    sa.Column('gols_casa', sa.Integer(), nullable=True),
    sa.Column('gols_visitante', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(length=1), nullable=True),
    sa.Column('url_fbref', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('agendada', 'em_andamento', 'finalizada', 'cancelada')", name='ck_partidas_status'),
    sa.CheckConstraint('clube_casa_id != clube_visitante_id', name='ck_partidas_clubes_diferentes'),
    sa.ForeignKeyConstraint(['clube_casa_id'], ['clubes.id'], ),
    sa.ForeignKeyConstraint(['clube_visitante_id'], ['clubes.id'], ),
    sa.ForeignKeyConstraint(['competicao_id'], ['competicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_partidas_casa', 'partidas', ['clube_casa_id'], unique=False)
    op.create_index('idx_partidas_competicao', 'partidas', ['competicao_id'], unique=False)
    op.create_index('idx_partidas_data', 'partidas', ['data_partida'], unique=False)
    op.create_index('idx_partidas_status', 'partidas', ['status'], unique=False)
    op.create_index('idx_partidas_temporada', 'partidas', ['temporada'], unique=False)
    op.create_index('idx_partidas_visitante', 'partidas', ['clube_visitante_id'], unique=False)
    op.create_table('posts_redes_sociais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clube_id', sa.Integer(), nullable=False),
    sa.Column('rede_social', sa.String(length=50), nullable=False, comment="Plataforma de rede social (ex: 'Twitter', 'Instagram', 'Facebook')"),
    sa.Column('post_id', sa.String(length=100), nullable=False, comment='ID único do post na plataforma de origem'),
    sa.Column('conteudo', sa.Text(), nullable=False, comment='Conteúdo textual do post'),
    sa.Column('data_postagem', sa.DateTime(), nullable=False, comment='Data e hora em que o post foi publicado'),
    sa.Column('curtidas', sa.Integer(), nullable=False, comment='Número de curtidas/reactions do post'),
    sa.Column('comentarios', sa.Integer(), nullable=False, comment='Número de comentários no post'),
    sa.Column('compartilhamentos', sa.Integer(), nullable=False, comment='Número de compartilhamentos/retweets'),
    sa.Column('url_post', sa.Text(), nullable=True, comment='URL direta para o post na rede social'),
    sa.Column('midia_url', sa.Text(), nullable=True, comment='URL da mídia anexada ao post (imagem/vídeo)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clube_id'], ['clubes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rede_social', 'post_id', name='uq_post_rede_social_id')
    )
    op.create_index('idx_posts_redes_sociais_clube', 'posts_redes_sociais', ['clube_id'], unique=False)
    op.create_index('idx_posts_redes_sociais_data', 'posts_redes_sociais', ['data_postagem'], unique=False)
    op.create_index('idx_posts_redes_sociais_post_id', 'posts_redes_sociais', ['post_id'], unique=False)
    op.create_index('idx_posts_redes_sociais_rede', 'posts_redes_sociais', ['rede_social'], unique=False)
    op.create_table('records_vs_opponents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clube_id', sa.Integer(), nullable=False),
    sa.Column('oponente_id', sa.Integer(), nullable=False),
    sa.Column('jogos_total', sa.Integer(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=True),
    sa.Column('empates', sa.Integer(), nullable=True),
    sa.Column('derrotas', sa.Integer(), nullable=True),
    sa.Column('gols_pro', sa.Integer(), nullable=True),
    sa.Column('gols_contra', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('clube_id != oponente_id', name='ck_records_clubes_diferentes'),
    sa.ForeignKeyConstraint(['clube_id'], ['clubes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oponente_id'], ['clubes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clube_id', 'oponente_id', name='uq_record_clube_oponente')
    )
    op.create_index('idx_records_clube', 'records_vs_opponents', ['clube_id'], unique=False)
    op.create_index('idx_records_oponente', 'records_vs_opponents', ['oponente_id'], unique=False)
    op.create_table('estatisticas_jogador_competicao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('competicao_id', sa.Integer(), nullable=False),
    sa.Column('temporada', sa.String(length=20), nullable=False),
    sa.Column('jogos', sa.Integer(), nullable=True),
    sa.Column('jogos_titularidade', sa.Integer(), nullable=True),
    sa.Column('minutos', sa.Integer(), nullable=True),
    sa.Column('gols', sa.Integer(), nullable=True),
    sa.Column('assistencias', sa.Integer(), nullable=True),
    sa.Column('cartoes_amarelos', sa.Integer(), nullable=True),
    sa.Column('cartoes_vermelhos', sa.Integer(), nullable=True),
    sa.Column('chutes', sa.Integer(), nullable=True),
    sa.Column('chutes_no_gol', sa.Integer(), nullable=True),
    sa.Column('passes_certos', sa.Integer(), nullable=True),
    sa.Column('passes_tentados', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True, comment='Expected Goals do jogador'),
    sa.Column('xa', sa.Float(), nullable=True, comment='Expected Assists do jogador'),
    sa.Column('posicao_principal', sa.String(length=20), nullable=True, comment='Posição principal jogada na competição'),
    sa.Column('minutos_por_jogo', sa.Float(), nullable=True, comment='Média de minutos por jogo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competicao_id'], ['competicoes.id'], ),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jogador_id', 'competicao_id', 'temporada', name='uq_estatistica_jogador_competicao_temporada')
    )
    op.create_index('idx_estatisticas_jogador_comp_competicao', 'estatisticas_jogador_competicao', ['competicao_id'], unique=False)
    op.create_index('idx_estatisticas_jogador_comp_jogador', 'estatisticas_jogador_competicao', ['jogador_id'], unique=False)
    op.create_index('idx_estatisticas_jogador_comp_temporada', 'estatisticas_jogador_competicao', ['temporada'], unique=False)
    op.create_table('estatisticas_jogador_geral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('temporada', sa.String(length=20), nullable=False),
    sa.Column('jogos', sa.Integer(), nullable=True),
    sa.Column('jogos_titularidade', sa.Integer(), nullable=True),
    sa.Column('minutos', sa.Integer(), nullable=True),
    sa.Column('gols', sa.Integer(), nullable=True),
    sa.Column('assistencias', sa.Integer(), nullable=True),
    sa.Column('cartoes_amarelos', sa.Integer(), nullable=True),
    sa.Column('cartoes_vermelhos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jogador_id', 'temporada', name='uq_estatistica_jogador_geral_temporada')
    )
    op.create_index('idx_estatisticas_jogador_geral_jogador', 'estatisticas_jogador_geral', ['jogador_id'], unique=False)
    op.create_index('idx_estatisticas_jogador_geral_temporada', 'estatisticas_jogador_geral', ['temporada'], unique=False)
    op.create_table('estatisticas_partidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('posse_bola_casa', sa.Float(), nullable=True),
    sa.Column('posse_bola_visitante', sa.Float(), nullable=True),
    sa.Column('chutes_casa', sa.Integer(), nullable=True),
    sa.Column('chutes_visitante', sa.Integer(), nullable=True),
    sa.Column('chutes_no_gol_casa', sa.Integer(), nullable=True),
    sa.Column('chutes_no_gol_visitante', sa.Integer(), nullable=True),
    sa.Column('escanteios_casa', sa.Integer(), nullable=True),
    sa.Column('escanteios_visitante', sa.Integer(), nullable=True),
    sa.Column('faltas_casa', sa.Integer(), nullable=True),
    sa.Column('faltas_visitante', sa.Integer(), nullable=True),
    sa.Column('cartoes_amarelos_casa', sa.Integer(), nullable=True),
    sa.Column('cartoes_amarelos_visitante', sa.Integer(), nullable=True),
    sa.Column('cartoes_vermelhos_casa', sa.Integer(), nullable=True),
    sa.Column('cartoes_vermelhos_visitante', sa.Integer(), nullable=True),
    sa.Column('xg_casa', sa.Float(), nullable=True, comment='Expected Goals do time da casa'),
    sa.Column('xg_visitante', sa.Float(), nullable=True, comment='Expected Goals do time visitante'),
    sa.Column('xa_casa', sa.Float(), nullable=True, comment='Expected Assists do time da casa'),
    sa.Column('xa_visitante', sa.Float(), nullable=True, comment='Expected Assists do time visitante'),
    sa.Column('formacao_casa', sa.String(length=20), nullable=True, comment='Formação tática do time da casa (ex: 4-3-3)'),
    sa.Column('formacao_visitante', sa.String(length=20), nullable=True, comment='Formação tática do time visitante (ex: 4-3-3)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_estatisticas_partida', 'estatisticas_partidas', ['partida_id'], unique=False)
    op.create_index('idx_estatisticas_partida_formacao', 'estatisticas_partidas', ['formacao_casa', 'formacao_visitante'], unique=False)
    op.create_index('idx_estatisticas_partida_xg', 'estatisticas_partidas', ['xg_casa', 'xg_visitante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_estatisticas_partida_xg', table_name='estatisticas_partidas')
    op.drop_index('idx_estatisticas_partida_formacao', table_name='estatisticas_partidas')
    op.drop_index('idx_estatisticas_partida', table_name='estatisticas_partidas')
    op.drop_table('estatisticas_partidas')
    op.drop_index('idx_estatisticas_jogador_geral_temporada', table_name='estatisticas_jogador_geral')
    op.drop_index('idx_estatisticas_jogador_geral_jogador', table_name='estatisticas_jogador_geral')
    op.drop_table('estatisticas_jogador_geral')
    op.drop_index('idx_estatisticas_jogador_comp_temporada', table_name='estatisticas_jogador_competicao')
    op.drop_index('idx_estatisticas_jogador_comp_jogador', table_name='estatisticas_jogador_competicao')
    op.drop_index('idx_estatisticas_jogador_comp_competicao', table_name='estatisticas_jogador_competicao')
    op.drop_table('estatisticas_jogador_competicao')
    op.drop_index('idx_records_oponente', table_name='records_vs_opponents')
    op.drop_index('idx_records_clube', table_name='records_vs_opponents')
    op.drop_table('records_vs_opponents')
    op.drop_index('idx_posts_redes_sociais_rede', table_name='posts_redes_sociais')
    op.drop_index('idx_posts_redes_sociais_post_id', table_name='posts_redes_sociais')
    op.drop_index('idx_posts_redes_sociais_data', table_name='posts_redes_sociais')
    op.drop_index('idx_posts_redes_sociais_clube', table_name='posts_redes_sociais')
    op.drop_table('posts_redes_sociais')
    op.drop_index('idx_partidas_visitante', table_name='partidas')
    op.drop_index('idx_partidas_temporada', table_name='partidas')
    op.drop_index('idx_partidas_status', table_name='partidas')
    op.drop_index('idx_partidas_data', table_name='partidas')
    op.drop_index('idx_partidas_competicao', table_name='partidas')
    op.drop_index('idx_partidas_casa', table_name='partidas')
    op.drop_table('partidas')
    op.drop_index('idx_noticias_fonte', table_name='noticias_clubes')
    op.drop_index('idx_noticias_data', table_name='noticias_clubes')
    op.drop_index('idx_noticias_clube', table_name='noticias_clubes')
    op.drop_table('noticias_clubes')
    op.drop_index('idx_jogadores_posicao', table_name='jogadores')
    op.drop_index('idx_jogadores_pais', table_name='jogadores')
    op.drop_index('idx_jogadores_nome', table_name='jogadores')
    op.drop_index('idx_jogadores_clube_atual', table_name='jogadores')
    op.drop_index('idx_jogadores_ativo', table_name='jogadores')
    op.drop_table('jogadores')
    op.drop_index('idx_estatisticas_clube_temporada', table_name='estatisticas_clube')
    op.drop_index('idx_estatisticas_clube_competicao', table_name='estatisticas_clube')
    op.drop_index('idx_estatisticas_clube_clube', table_name='estatisticas_clube')
    op.drop_table('estatisticas_clube')
    op.drop_index('idx_links_tipo', table_name='links_para_coleta')
    op.drop_index('idx_links_status', table_name='links_para_coleta')
    op.drop_index('idx_links_processado', table_name='links_para_coleta')
    op.drop_index('idx_links_competicao', table_name='links_para_coleta')
    op.drop_table('links_para_coleta')
    op.drop_index('idx_clubes_pais', table_name='clubes')
    op.drop_index('idx_clubes_nome', table_name='clubes')
    op.drop_index('idx_clubes_ativo', table_name='clubes')
    op.drop_table('clubes')
    op.drop_table('paises_jogadores')
    op.drop_table('paises_clubes')
    op.drop_index('idx_competicoes_nome', table_name='competicoes')
    op.drop_index('idx_competicoes_contexto', table_name='competicoes')
    op.drop_index('idx_competicoes_ativa', table_name='competicoes')
    op.drop_table('competicoes')
    # ### end Alembic commands ###
