"""Adiciona tabela noticias_clubes

Revision ID: d8bdb9b0920d
Revises: d3ff1c5ece16
Create Date: 2025-08-06 23:11:38.490008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8bdb9b0920d'
down_revision = 'd3ff1c5ece16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticias_clubes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clube_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('url_noticia', sa.String(length=500), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('conteudo_completo', sa.Text(), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.Column('imagem_destaque', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clube_id'], ['clubes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_noticia')
    )
    op.create_index('idx_noticias_clube', 'noticias_clubes', ['clube_id'], unique=False)
    op.create_index('idx_noticias_data', 'noticias_clubes', ['data_publicacao'], unique=False)
    op.create_index('idx_noticias_fonte', 'noticias_clubes', ['fonte'], unique=False)
    op.alter_column('posts_redes_sociais', 'clube_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Referência ao clube dono do post',
               existing_nullable=False)
    op.alter_column('posts_redes_sociais', 'data_postagem',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='Data e hora em que o post foi publicado',
               existing_nullable=False)
    op.drop_index('idx_posts_redes_sociais_engajamento', table_name='posts_redes_sociais')
    op.drop_constraint('posts_redes_sociais_post_id_key', 'posts_redes_sociais', type_='unique')
    op.create_index('idx_posts_redes_sociais_post_id', 'posts_redes_sociais', ['post_id'], unique=False)
    op.create_unique_constraint('uq_post_rede_social_id', 'posts_redes_sociais', ['rede_social', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_post_rede_social_id', 'posts_redes_sociais', type_='unique')
    op.drop_index('idx_posts_redes_sociais_post_id', table_name='posts_redes_sociais')
    op.create_unique_constraint('posts_redes_sociais_post_id_key', 'posts_redes_sociais', ['post_id'])
    op.create_index('idx_posts_redes_sociais_engajamento', 'posts_redes_sociais', ['curtidas', 'comentarios', 'compartilhamentos'], unique=False)
    op.alter_column('posts_redes_sociais', 'data_postagem',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Data e hora em que o post foi publicado',
               existing_nullable=False)
    op.alter_column('posts_redes_sociais', 'clube_id',
               existing_type=sa.INTEGER(),
               comment='Referência ao clube dono do post',
               existing_nullable=False)
    op.drop_index('idx_noticias_fonte', table_name='noticias_clubes')
    op.drop_index('idx_noticias_data', table_name='noticias_clubes')
    op.drop_index('idx_noticias_clube', table_name='noticias_clubes')
    op.drop_table('noticias_clubes')
    # ### end Alembic commands ###
